#!/usr/bin/env python

import json
import sys
import re

with open('/tmp/.aws.json') as data_file:
    data = json.load(data_file)

machines = data['Reservations'].__len__() - 1

if sys.argv[1] == "-id":

	id = sys.argv[2]

	for machine in range(0, machines):
	    aws_id = data['Reservations'][machine]['Instances'][0]['InstanceId'].__str__()
	    if aws_id == id:
	        break

	tag_size = data['Reservations'][machine]['Instances'][0]['Tags'].__len__() - 1
	for tag in range(0, tag_size):
	    if data['Reservations'][machine]['Instances'][0]['Tags'][tag]['Key'] == "Name":
	        r_name = data['Reservations'][machine]['Instances'][0]['Tags'][tag]['Value']

	print "%s  =>:  %s" % (r_name, data['Reservations'][machine]['Instances'][0]['PrivateIpAddress'])

elif sys.argv[1] == "-ip":

	ip = sys.argv[2]

	for machine in range(0, machines):
		try:
			aws_ip = data['Reservations'][machine]['Instances'][0]['PrivateIpAddress']
			if aws_ip == ip:
				break
		except:
			continue

	tag_size = data['Reservations'][machine]['Instances'][0]['Tags'].__len__() - 1
	for tag in range(0, tag_size):
	    if data['Reservations'][machine]['Instances'][0]['Tags'][tag]['Key'] == "Name":
	        print data['Reservations'][machine]['Instances'][0]['Tags'][tag]['Value']

elif sys.argv[1] == "-name":

	name = sys.argv[2]

	for machine in range(0, machines):
		tag_size = data['Reservations'][machine]['Instances'][0]['Tags'].__len__() - 1
		for tag in range(0, tag_size):
		    if data['Reservations'][machine]['Instances'][0]['Tags'][tag]['Key'] == "Name":
		        if re.search(name, data['Reservations'][machine]['Instances'][0]['Tags'][tag]['Value']):
		        	try:
		        		priv_ip = data['Reservations'][machine]['Instances'][0]['PrivateIpAddress']
		        	except:
		        		priv_ip = "None"
		        	print "%s  =>:  %s" % (data['Reservations'][machine]['Instances'][0]['Tags'][tag]['Value'], priv_ip)

else:
	print "Wrong Parameters"



